Support customize spiffeID separator
bytedance/spire-workload-rs pull request #11
Opened 2022-08-26 09:48 UTC by loveyana

1. Add set_spiffe_separator function to set spiffeID separator, default: ":"
2. Add SPIFFEID_SEPARATOR and VALID_SPIFFEID_SEPARATORS variable
3. The list of valid spiffeID separator is ":", "-",  "." , "_"

2022-08-26 15:38 UTC, w93163red requested changes

2022-08-26 15:38 UTC, w93163red commented on src/lib.rs
> +    if !VALID_SPIFFEID_SEPARATORS.contains(&separator.chars().next().unwrap()){
生产代码避免使用unwrap()。
尤其是下面设计到读写锁的。如果拿不到锁，整个程序就crash了，应该是不符合预期的。

2022-08-26 15:38 UTC, w93163red commented on src/lib.rs
> +    pub static ref VALID_SPIFFEID_SEPARATORS: Vec<char> = vec![':', '-', '.', '_'];
SPIFFEID_SEPERATOR 可以使用无锁的atomicu8 代替我觉得会更好一些
https://doc.rust-lang.org/std/sync/atomic/struct.AtomicU8.html

然后后面再去做一些转换，这样可以避免掉拿锁的开销

2022-08-26 15:38 UTC, w93163red commented on src/spiffe.rs
> +        let separator = SPIFFEID_SEPARATOR.read().unwrap();
这里的写法会导致SPIFFEID_SEPARATOR 拿到锁不会及时释放，其实释放时机应该是seperator 拿到内容之后就应该释放掉了。相关锁操作应该保证最小的作用区间。
https://doc.rust-lang.org/std/sync/struct.RwLock.html
官方文档里 有用大括号括起来来限制scope的写法。或者另外起函数把这个包起来。

2022-08-26 15:38 UTC, w93163red commented on src/spiffe.rs
> +            let split_index = segment.find(&separator[0..1]);
这个地方如果未来都是简单合法的UTF-8的话 不会有太大问题……

如果是一些蛋疼的UTF-8的话 ，这里会导致程序直接崩溃。可以考虑下是不是使用get() 方法判断一下避免出现问题

2022-08-26 15:38 UTC, w93163red commented on src/spiffe.rs
> +                .map(|(name, value)| format!("{}{}{}", name, SPIFFEID_SEPARATOR.read().unwrap() ,value))
理由同上

2022-08-26 15:38 UTC, w93163red commented on src/spiffe.rs
> +                    SPIFFEID_SEPARATOR.read().unwrap(),
同上

2022-08-26 15:38 UTC, w93163red commented on src/spiffe.rs
> +            "spiffe://spiffe-test/ns_tce/ns_tce/r_us/vdc_useast2a/id_security.platform.kms_client",
vdc 名字改一些其他无关的

2022-08-29 03:32 UTC, loveyana commented on src/lib.rs
> +    if !VALID_SPIFFEID_SEPARATORS.contains(&separator.chars().next().unwrap()){
嗯嗯 前面判断了&str的长度必须为1，所以这里对于char为None偷了个懒，已经修改

2022-08-29 03:32 UTC, loveyana commented on src/lib.rs
> +    pub static ref VALID_SPIFFEID_SEPARATORS: Vec<char> = vec![':', '-', '.', '_'];
已替换RwLock 为 AtomicU8

2022-08-29 14:38 UTC, w93163red commented on src/spiffe.rs
> +                .map(|(name, value)| format!("{}{}{}", name, SPIFFEID_SEPARATOR.load(Ordering::SeqCst) as char ,value))
这个感觉被调用了多次  封装一下吧 getter/setter 啥的

2022-08-30 02:24 UTC, loveyana commented on src/spiffe.rs
> +                .map(|(name, value)| format!("{}{}{}", name, SPIFFEID_SEPARATOR.load(Ordering::SeqCst) as char ,value))
> 这个感觉被调用了多次 封装一下吧 getter/setter 啥的

这个formater在spiffeID和spiffeIDMatcher逻辑不一样没办法封装了

2022-08-30 02:29 UTC, closed without merging